server:
  host: "localhost"
  port: 3000

database:
  host: "mysql_db"
  port: 3306
  name: "mysql"
  user: "root"
  password: "Wce@2022"
  database: "todoapp"

redis:
  host: "redis_db"
  port: 6379
  password: "Redsecret"
  db: 0
