server:
  host: "localhost"
  port: 3000

database:
  host: "host.docker.internal"
  port: 3308
  name: "mysql"
  user: "root"
  password: "Wce@2022"
  database: "todoapp"

redis:
  host: "todo-redis"
  port: 6379
  password: "Redsecret"
  db: 0
